server:
  port: 8081
  servlet:
    context-path: /goodshouse
spring:
  datasource:
    url: 127.0.0.1
    username: test
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  shiro:
    timeout: 18000

mybatis:

